name: release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup mise
        uses: jdx/mise-action@v2
      - name: test
        run: mise run test
      - name: build
        run: mise run dist
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghq-alfred.alfredworkflow
          path: ./ghq-alfred.alfredworkflow
      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            "./ghq-alfred.alfredworkflow" \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes
